/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is automatically generated by TanStack Router.
// It is kept in sync here so deployed builds register every file route.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GanchosRouteImport } from './routes/ganchos'
import { Route as InfluencersRouteImport } from './routes/influencers'
import { Route as ProjetosRouteImport } from './routes/projetos'
import { Route as ProjetoIdRouteImport } from './routes/projeto/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

const GanchosRoute = GanchosRouteImport.update({
  id: '/ganchos',
  path: '/ganchos',
  getParentRoute: () => rootRouteImport,
} as any)

const InfluencersRoute = InfluencersRouteImport.update({
  id: '/influencers',
  path: '/influencers',
  getParentRoute: () => rootRouteImport,
} as any)

const ProjetosRoute = ProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => rootRouteImport,
} as any)

const ProjetoIdRoute = ProjetoIdRouteImport.update({
  id: '/projeto/$id',
  path: '/projeto/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ganchos': typeof GanchosRoute
  '/influencers': typeof InfluencersRoute
  '/projetos': typeof ProjetosRoute
  '/projeto/$id': typeof ProjetoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ganchos': typeof GanchosRoute
  '/influencers': typeof InfluencersRoute
  '/projetos': typeof ProjetosRoute
  '/projeto/$id': typeof ProjetoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ganchos': typeof GanchosRoute
  '/influencers': typeof InfluencersRoute
  '/projetos': typeof ProjetosRoute
  '/projeto/$id': typeof ProjetoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ganchos' | '/influencers' | '/projetos' | '/projeto/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ganchos' | '/influencers' | '/projetos' | '/projeto/$id'
  id: '__root__' | '/' | '/ganchos' | '/influencers' | '/projetos' | '/projeto/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GanchosRoute: typeof GanchosRoute
  InfluencersRoute: typeof InfluencersRoute
  ProjetosRoute: typeof ProjetosRoute
  ProjetoIdRoute: typeof ProjetoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ganchos': {
      id: '/ganchos'
      path: '/ganchos'
      fullPath: '/ganchos'
      preLoaderRoute: typeof GanchosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/influencers': {
      id: '/influencers'
      path: '/influencers'
      fullPath: '/influencers'
      preLoaderRoute: typeof InfluencersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos': {
      id: '/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof ProjetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projeto/$id': {
      id: '/projeto/$id'
      path: '/projeto/$id'
      fullPath: '/projeto/$id'
      preLoaderRoute: typeof ProjetoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GanchosRoute: GanchosRoute,
  InfluencersRoute: InfluencersRoute,
  ProjetosRoute: ProjetosRoute,
  ProjetoIdRoute: ProjetoIdRoute,
}

export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
